- name: configuaring the backend
  hosts: backend
  become: yes
  tasks:
  - name: disable nodejs
  ansible.builtin.module: dnf module disable nodejs -y

  - name: enable nodejs20
  ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
  ansible.builtin.dnf:
  name: nodejs
  state: installed
    
  - name: create expense user
  ansible.builtin.user:
  name: expense
    