- name: Configuring the backend
  hosts: backend
  become: yes
  tasks:
  - name: disable Node.
    ansible.builtin.command: dnf module disable nodejs -y
        

  - name: Enable Node js 20 module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install Node.js
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create expense user
    ansible.builtin.user:
      name: expense
  
  - name: create app directory
    ansible.builtin.file:
    path: /app
    state: directory
