- name: configuaring mysql
hosts: db
become: yes
tasks:
  - name: install mysql
    ansible.builtin.dnf:
    name: mysql-server
    state: present
##google it -- ansible start service and enable
  - name: start mysqld
    ansible.builtin.service:
    name: mysqld
    state: started
    enable: yes

  ## check password is already set-up ot not
  ##ggogle-- ansible my sql module 
  - name: set mysql root password
    community.my.sql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: db.vijayganisetti.online
    filter: version
    ignore_errors: yes
    register: mysql_info

  - name: print output
    ansible.builtin.debug:
    msg: "{{ mysql_info}}"